name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies & Build Web
        run: |
          npm install
          npm run build

      - name: Initialize Capacitor
        run: |
          npm install @capacitor/core @capacitor/cli
          npx cap init "Password Manager" "com.hmo.passwordmanager" --web-dir=dist
          npm install @capacitor/android
          npx cap add android

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build APK with Gradle
        run: |
          npx cap sync
          cd android && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PasswordManager-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
          
